33cn/chain33

- types/reflect.go
- wallet/wallet_test.go
- wallet/walletbizpolicy.go
1. 新增钱包默认处理的策略walletbizpolicy.go，实现钱包基础的功能代码
2. 去掉wallet_test.go中有关ticket状态检查
3. 调整QueryData中重复名称注册冲突导致panic的提示信息
> 修复系统框架中没有默认处理钱包功能导致钱包测试用例过不了的BUG

- rpc/client.go
修改GetAllExecBalance的传参，使用执行器名称带上平行链前缀。 使其适配平行链上的查询。
可以加上这个注释：
fixed #63
> fix for issue_63 

- blockchain/chain.go
最新版本存在这方面的隐患，目前的代码处理：就是启动blockchian时在InitIndexAndBestView函数中通过height获取blockheader 然后将blockheader信息加载到缓存中，如果此时从数据库获取blockheader失败，会直接退出此函数导致ChainView 和index没有被初始化。
修改方案：在InitIndexAndBestView函数中，通过height获取blockheader失败时直接panic掉。
> add by hyb for issues217

- blockchain/blockstore.go
- blockchain/chain.go
- blockchain/sequences.go
- types/error.go
- types/jsonpb/jsonpb_test_proto/test_objects.proto
- types/proto/blockchain.proto
- types/proto/common.proto
- types/proto/rpc.proto
- types/proto/statistic.proto
- types/rpc.pb.go
1，chain33启动之后增加isRecordBlockSequence配置的合法性检测
2，当isRecordBlockSequence没有被使能时不允许添加seq callback
3，在reindex时需要过滤掉seqCBPrefix和seqCBLastNumPrefix的key
> add by hyb for isRecordBlockSequenceValid

- rpc/types/code.go
- types/executor.go
- types/executor_test.go
- types/jsonpb/jsonpb.go
- types/types.go
- types/types_test.go
> query transaction when bytes string is utf8, encode to string, not hex

- system/dapp/commands/bty.go
- wallet/wallet_proc.go
1. 钱包转发add/del block消息时，获取注册的执行器名，改为getParaExec，适配平行链
2. 隐私交易三步构建之前写在bty中，已经迁移到插件的隐私合约下
> Wallet support parachain

- executor/executor.go
EVM合约在查询数据时比较特殊，通过ABI查询和合约交易查询调用都可以查询数据，走的是同样的流程innerExec，在这个方法里面存在高度判断
> add height set

- account/account.go
平行链上面token资产查询，存在前缀混乱的情况 
close 33cn/plugin#227
> 修复平行链上面token资产查询，存在前缀混乱的bug

- rpc/jrpchandler.go
- rpc/server_test.go
fixed #311 
这几个接口是stat 相关的接口，目前，因为stat 相关的实现上存在错误，所以像删除这些接口。
同时，我们需要多 LocalList 和 LocalGet 两个接口做一个限制，需要限制分页的数目，以及读取的数目。
fixed #321
> 在chain33 中 删除一些ticket 相关的接口

- cmd/chain33/chain33.test.toml
- cmd/chain33/chain33.toml
- system/mempool/check.go
- system/mempool/mempool_test.go
检查交易的判断条件里用到的判断依据由const里的maxTxNumPerAccount改成了cfg里的MaxTxNumPerAccoun，删除了timeline中冗余的配置参数
> 配置文件里mempool的用户交易数最大限制无效

- account/account.go
- account/execaccount.go
- common/hash.go
- common/merkle/merkle.go
- common/merkle/merkle_test.go
- executor/execenv.go
- util/exec.go
- util/util_test.go
增加多线程计算merkle tree 的功能
在mac pro 测试，10万个 merkle tree ，从 79ms 降低为 25ms
大幅度减少 内存分配的数量 （account 模块中）
目前 ExecBlock 测试的结果为：
10	 188000355 ns/op	71508354 B/op	 1211029 allocs/op
> 增加多线程计算merkle tree 的功能

- queue/client.go
- queue/queue_test.go
回复错误的时候，直接回复 error msg ，如果用 ReplyErr 会引起问题。
TODO: ReplyErr 需要重新命名，以防止出现类似的误解。
> reply close error

- rpc/grpcclient/client.go
给grpc 的客户端加上 keepalive， 防止tcp链接异常导致请求卡住。
> add keepalive for grpc client

- system/dapp/register.go
> exec allow add height

- common/skiplist/skiplist.go
- common/skiplist/skiplist_test.go
跳跃表迭代器新增Prev()和Next()用于迭代下一个节点和上一个节点，WalkS用于迭代SkipValue，弥补Walk函数无法迭代获取Score
> Skiplist 添加WalkS

- blockchain/blocksyn.go
- blockchain/chain_test.go
- blockchain/download.go
- blockchain/proc.go
目前的处理是只要区块下载成功就通知下载任务继续下一个区间区块的下载，这样在机械硬盘的电脑写数据库比较慢的情况下，导致 blockchain这边积压很多需要写数据库的goroutine资源。
修改成在快速下载区块保存到数据库之后再通知下载任务继续下个区间的下载。这样可以减少goroutine资源的使用。
在节点启动后首先需要执行完上次已经下载并临时存贮在db中的blocks时，要允许close chain进程，所以取消go chain.FastDownLoadBlocks() 的WaitGroup等待处理
> add by hyb for goroutine

- system/dapp/commands/bty.go
- system/dapp/commands/types/utils.go
解决平行链命令行进行coins withdraw操作时，合约地址不正确
```
chain33-para send bty withdraw -e paracross -a 1 -k addr
```
采用如上命令，to地址是paracross而不是平行链下的paracross地址
> fix coins withdraw command

- blockchain/restore.go
- cmd/chain33/bityuan.toml
- cmd/chain33/chain33.toml
- types/cfg.go
toml中加了升级store时候使能重新执行exec_local，默认不开启，平行链或者测试链升级store时候需要开启
> add update storedb re exec_local

- wallet/wallet_proc.go
修改钱包按照实际的to地址存储交易信息，主要是平行链交易tx.GetTo()获取的是平行链的合约地址，不是真实的接受地址，获取真实的接受地址需要通过tx.GetRealToAddr（）来获取
> add by hyb for issues493 getrealtoaddr

- build/system-test-rpc.sh
rpc-test-chain33_GetAllExecBalance
在返回多个帐号时， 判断出错
> fix rpc-test-chain33_GetAllExecBalance

- rpc/http.go
fix #534 
>rpc解析非法参数后，未处理空指针情况
> fix rpc param check

- system/mempool/base.go
- system/mempool/check.go
配置文件里新增一个阶梯手续费的开关
当这个开关处于开启状态时候
mempool里的交易总字节数大于等于区块最大字节数二十分之一或者交易数量大于区块最大交易数的二分之一时，手续费率就会提升百倍
mempool里的交易总字节数大于等于区块最大字节数的百分之一或者交易数量大于等于区块最大交易数量的十分之一时，手续费率就会提升十倍
手续费率最高不会超过0.1
该合适的手续费率目前是通过排队方式的合适手续费率获得，默认排队方式是timeline，合适手续费率为配置里mempool的minTxFee，即最小手续费
修改了之前 https://github.com/33cn/chain33/pull/538 判断的逻辑
> Mempool levelfee

- build/system-test-rpc.sh
fix chain33_GetCoinSymbol 在平行链返回 symbol 为 配置值, 不是bty
> fix chain33_GetCoinSymbol 在平行链返回 symbol 为 配置值

- blockchain/blockstore.go
- blockchain/blockstore_test.go
- blockchain/chain.go
1，在区块回滚的过程中lastblock和lastseq对应的block不是同一个区块，所以取消这个lastblock和lastseq对应block hash值的比较。
2，不允许用户关闭isRecordBlockSequence功能。
> add by hyb for rollback-seq

- p2p/downloadblocks.go
目前p2p下载区块基于grpc 服务端流式调用，由于改成了接收到数据立即返回，没有等待Recv流io.EOF，grpc内部相关的gorouting没有释放，造成泄漏，需要完成调用后主动结束stream，即时释放资源 fixed 33cn/plugin#581
> p2p:add manual cancel download grpc stream

- blockchain/blocksyn.go
- blockchain/chain_test.go
- blockchain/download.go
- blockchain/task.go
- blockchain/task_test.go
解决issues566问题：
在task任务模块增加一个超时回调处理接口。
当在快速同步模式时，挂接下载超时调用接口DownLoadTimeOutProc从而再次触发从超时的高度继续同步数据
普通下载模式是通过定时器触发的，所以普通下载模式不需要挂接超时的处理函数。
目前下载区块主要分三种情况：
a，节点启动后的快速同步；
b，定时触发的普通同步 ；
c，检测到分叉之后的回滚数据的下载处理；
限制条件：
1，在普通同步模式时，如果检测到有分叉需要回滚处理，此时需要暂停普通同步的任务，等分叉处理之后再开启普通同步。
,2，当正在处理分叉回滚时，不允许触发定时的普通同步数据，直到分叉回滚处理结束后再触发普通同步
> add by hyb for fast download timeout proc

- system/dapp/commands/wallet.go
- wallet/common/store.go
- wallet/wallet_test.go
修改WalletTxList接口的实现：
现在代码实现：当调用此接口时传入fromTx为空时，默认从最新的交易开始获取，没有使用direction的值。所以现有代码只能从最新的交易开始获取，无法从最早的交易开始获取
新的代码实现：通过fromTx和direction一起组合使用。从最新/最早的交易开始获取
1，当fromTx == nil  && direction == 0，从最新的一笔交易开始获取
2，当fromTx == nil  && direction == 1，从最早的一笔交易开始获取
影响：
目前钱包项目获取最新的交易时传入的fromTx == nil ，direction的值可能是0或者1.
因为direction值没有被使用，所以direction的值填写0或者1都可以获取最新的交易。
如果钱包项目获取最新的交易时传入的direction值是1的话，
这次底层代码升级之后上层钱包项目需要同步升级。
按照新的规则传入参数来获取最新/最早的交易。
> add by hyb for get wallet tx list from last or first

- blockchain/query_tx.go
- common/version/version.go
1，新的代码不支持PrefixCount查询地址交易计数，在 executor/localdb.go PrefixCount  导致升级上来的数据库使用PrefixCount方式查询地址交易计数失败
解决方案：
而现有的节点都已经升级了localdb到1.0.0版本，也就是都支持通过GetAddrTxsCount来获取地址交易 计数。所以ProcGetAddrOverview接口的实现统一修改成通过GetAddrTxsCount来获取地址交易计数
2，在升级localdb时，在删除tx相关的key值，没有过滤记录storedb版本信息的key值StoreDBMeta。导致每次升级完localdb之后都会升级storedb。
解决方案：将记录storedb版本信息的key值 ，添加version.GetLocalDBKeyList()中。这样在调用BlockStore.delAllKeys()时，可以过滤出不需要删除的key值
close #646
> add by hyb for issues646

- blockchain/blockstore.go
- blockchain/blockstore_test.go
在tx交易去重处理时，首先检测短hash是否重复，不重复直接返回，如果短hash有重复需要再校验一下tx交易的全hash是否有重复。从而避免那种全hash不一致，但是短hash一致时的交易
> add by hyb for tx shorthash duplicate

- p2p/blockcache.go
- p2p/const.go
- p2p/filterrepeatdata.go
- p2p/p2pcli.go
- p2p/p2pserver.go
- p2p/peer.go
- p2p/process.go
- p2p/process_test.go
fix 33cn/plugin#592
>问题是本地发出的交易未增加到接收重复过滤
同时增加了交易和区块发送重复过滤，有两种情况：
1. 节点间维护了两条连接（分别客户端服务端）时，只触发首次发送
2. 在交易发送前，可能接收到其他节点广播过来同一个交易，对这些节点不再发送
补充p2p广播处理流程日志
> Update p2p broadcast filter

- wallet/wallet.go
wallet data race 应该是GetPrivKeyByAddr接口没有加钱包的锁导致
> add by hyb for wallet data race

- wallet/wallet.go
- wallet/wallet_proc.go
钱包模块死锁。ticket合约的wallet插件在调用钱包的GetPrivKeyByAddr接口之前已经锁住了钱包。
所以在GetPrivKeyByAddr接口中不需要再加锁
> add by hyb for wallet-deadlock

- wallet/seed.go
- wallet/sendtx.go
- wallet/wallet.go
- wallet/wallet_proc.go
- wallet/wallet_test.go
将wallet模块中的SignType全局变量，添加到wallet实例中，使用wallet的 锁来保护
该钱包插件模块提供的借口：SendTransaction和SendToAddress提供钱包的锁功能
> add by hyb for wallet lock

- blockchain/blocksyn.go
- blockchain/chain.go
- blockchain/chain_test.go
- types/cfg.go
问题描述：
目前联盟链节点可能会出现区块不能广播到其他节点导致整个网络的共识卡主。
修改方案：
增加一个节点区块高度长时间不增涨的超时处理。
如果节点区块高度长时间不增涨，超过预设置的超时时间，并且本节点和最高节点只差一个区块时，
本节点向最高节点主动请求最新的区块
使用说明：
配置文件blockchain模块增加一个区块上链超时时间的设置onChainTimeout，单位是秒。系统默认是0，不开启这个超时检测的处理。联盟链可以根据各自的情况设置这个超时时间
close 33cn/plugin#646
> add by hyb for issues-646

- p2p/p2pcli.go
- p2p/process.go
老版本发来的交易不带Route.TTL信息，新版本解析出来是空指针
> p2p:fix nil route info from old version

- common/version/version.go
- p2p/p2pcli.go
- p2p/process.go
老版本发来的交易不带Route.TTL信息，新版本解析出来是空指针
> Fix nil route info from old version

- p2p/peer.go
- p2p/process.go
* 短哈希交易广播，对方节点不存在交易时， 会再次请求全交易广播
* 本地发送过滤未考虑这种情况，短哈希广播时不应该增加发送过滤
* 修正peername过滤键值
> p2p:fix light tx broadcast

- blockchain/proc.go
- blockchain/process.go
增加处理广播区块的限制，只处理落后自己10000之内和超前128之内的广播区块。
1，修改前的代码重现panic问题
2，修改成只处理落后10000个和超前128个之内的广播区块：
当前高度是43101，收到落后的广播区块33099和33100不做处理直接返回
> add by hyb for broadcast block limit

- blockchain/query_tx.go
修复： ProcGetAddrOverview: 在没有资产，有交易的情况下，返回出错。
close #702
> Fix get addr overview 6.3

- rpc/client.go
- rpc/client_test.go
- rpc/grpchandler.go
- rpc/jrpchandler.go
- rpc/rpc_real_test.go
- types/error.go
- wallet/wallet_proc.go
fix #706 
* 修正CreateNoBalance接口，未处理expire参数错误
* 将CreateNoBalance内部接口合二为一
> 相关说明
* 交易组过期，设置其中一笔即可生效
* SignRawTx接口设置了首笔过期， 不需要修改
> rpc:fix CreateNoBalance rpc tx expire setting

- common/skiplist/queue.go
- common/skiplist/queue_test.go
- system/mempool/base.go
- system/mempool/cache.go
- system/mempool/simplequeue.go
fix #698 
目前的方式是，扩展queue接口增加CacheBytes函数，由底层的cache缓存自己管理好cacheSize
> mempool:update calc total cache bytes

- queue/queue.go
捕捉terminated信号，保证kill pid可以安全退出后台运行的chain33
相关补充说明文档见confluence:
https://confluence.33.cn/pages/viewpage.action?pageId=18679144
> notify SIGTERM for safe exit

- rpc/client.go
- rpc/client_test.go
1. 修复限制平行链设置区块高度作为过期的逻辑, 考虑特殊永不过期expire=0的情况
2. 增加expire为空时默认过期时间, 为永不过期
> rpc:fix createNoBalanceTx expire setting

- blockchain/restore.go
- common/db/db.go
- common/db/db_test.go
- common/db/go_level_db_test.go
- common/db/list_helper.go
- executor/executor.go
- executor/executor_test.go
- pluginmgr/manager.go
- system/dapp/driver.go
- types/event.go
- wallet/common/store.go
合约增加升级机制：
1. 升级只允许升级 localdb，不能访问 statedb
2. locals set 后，并且 upgrade 函数返回 没有err 那么自动提交到数据库中，否则，会回滚set 的内容。
3. TODO： 补充单元测试
> add upgrade option when blockchain is start

- p2p/peer.go
取消订阅时遗漏了topic, 此时不能释放sub最初分配的channel, 导致内存泄漏, 修改为close时释放所有
> p2p:add peer close with unsub all topics

- client/queueprotocol_test.go
```
func TestQueueProtocolAPI(t *testing.T) {
var option client.QueueProtocolOption
option.SendTimeout = time.Millisecond
option.WaitTimeout = 2 * time.Millisecond
_, err := client.New(nil, nil)
if err == nil {
t.Error("client.New(nil, nil) need return error")
}
var q = queue.New("channel")
qc, err := client.New(q.Client(), &option)
if err != nil {
t.Errorf("client.New() cause error %v", err)
}
if qc == nil {
t.Error("queueprotoapi object is nil")
}
_, err = qc.Notify("", 1, "data")
assert.Nil(t, err)
}
```
本地执行几十次未能复现。低优先级消息队列容量defaultLowChanBuffer = 40960，可以排除消息队列已满导致的超时问题，初步考虑是因为超时时间设置的太短引起的问题。
option.SendTimeout原来是100纳秒，即千万分之一秒，等待时间太短可能导致因为机器具体执行环境导致超时。考虑到生产环境不会等待如此短的时间，ut中把等待时间设置为1毫秒即千分之一秒，既可以覆盖生产环境的极端使用场景，也不会对ut执行效率造成影响
> Fix queue ut

- blockchain/proc.go
- p2p/event.go
- p2p/utils/blockcache.go
- p2p/utils/util_test.go
- system/p2p/dht/p2p.go
- system/p2p/dht/p2p_test.go
- system/p2p/dht/protocol/broadcast/block.go
- system/p2p/dht/protocol/broadcast/block_test.go
- system/p2p/dht/protocol/broadcast/broadcast.go
- system/p2p/dht/protocol/broadcast/broadcast_test.go
- system/p2p/dht/protocol/broadcast/const.go
- system/p2p/dht/protocol/broadcast/query.go
- system/p2p/dht/protocol/broadcast/query_test.go
- system/p2p/dht/protocol/broadcast/tx.go
- system/p2p/dht/protocol/download/download.go
- system/p2p/dht/protocol/download/download_test.go
- system/p2p/dht/protocol/headers/header.go
- system/p2p/dht/protocol/headers/header_test.go
- system/p2p/dht/protocol/peer/peerinfo.go
- system/p2p/dht/protocol/peer/peerinfo_test.go
- system/p2p/dht/protocol/types/protocol.go
- system/p2p/dht/protocol/types/stream.go
- system/p2p/dht/types/types.go
* 区块是否轻广播阈值，修改为按照区块大小，默认大于100k进行区块轻广播，支持配置minLtBlockSize
* 轻广播接收端缓存（本地缺失交易时组装部分进行缓存）空间大小，修改为可配置
* 删除轻广播发送端区块缓存，修改为直接从blockchain模块获取，blockchain模块默认缓存了最近的128个区块，p2p不再进行区块缓存
* 调整广播相关日志，减少debug日志量
fix #825
> Update dht broadcast

- wallet/common/mine_status_report.go
- wallet/sendtx.go
- wallet/wallet.go
- wallet/wallet_test.go
RegisterMineStatusReporter 函数处理时需要检测当前的共识和wallet插件是否有冲突，不允许注册有冲突的钱包插件 。
相应的plugin工程的ticket和pos33  wallet 插件需要实现PolicyName() 方法，返回各自的wallet插件名字
> add by hyb for Consensus policy Conflict

- blockchain/chain.go
- blockchain/process.go
- blockchain/push.go
- blockchain/push_test.go
- blockchain/rollback.go
1.解决ut过程中push的data race问题，
解决方法，增加一个读写锁，该办法纯粹是为ut解决问题，实际blockchain运行过程中，不会发生该数据竞争问题，一定程度上会影响系统的开销，但是该读写锁的频率是出块的频率，没有大的影响。
> bug fix for data race

- blockchain/chain.go
- blockchain/process.go
- blockchain/push.go
- blockchain/push_test.go
- blockchain/rollback.go
在push的ut中删除多余的赋值操作，这样在push的功能代码中就不需要使用rwlock机制，减少为了UT而增加冗余代码
> to fix push ut's data race

- blockchain/push_test.go
通过使用新构建的blockchain的方式，避免在ut测试中的datarace
> use another blockchain to fix data race due to value assign

- blockchain/chain_test.go
- blockchain/query_tx.go
删除获取proof时没有必要的打印，此时打印的是branch hash值所以没有必要再转换成hex打印出来。
test中hash输出时使用hex格式
close #878
> add by hyb for print hex string

- blockchain/chain_test.go
- system/mempool/check.go
- types/tx.go
- types/tx_test.go
调整ResetHashCache位置，放在交易费检查之后，避免hashCache改变原始交易的size，导致临界情况交易费计算变化
> reset tx hash cache after tx check

- types/tx.go
- types/tx_test.go
fix #891
* 交易check fee会分别在mempool， exec模块调用，通过统一修改GetRealFee，对hash cache字段大小进行屏蔽，不计入fee计算
> fix calc tx fee

- system/dapp/coins/types/types.go
- system/dapp/coins/types/types_test.go
coins  交易处理的对象是主币.  如果根据交易的symbol 输出 asset是错误的.
查询交易结果输出的asset 不对, 会引起误解.
> 忽略coins 转账时, 交易中输入的symbol. 

- blockchain/query_block.go
修改通过区块height获取区块hash的接口。
不再通过block信息计算区块hash的方式获取
直接从本地数据库中存储的height->hash对应关系中获取区块hash。
> add by hyb for ProcGetBlockHash

- blockchain/cache.go
- blockchain/chain.go
- blockchain/process.go
- blockchain/query_tx.go
- types/cfg.go
- types/const.go
修改blockchian模块最新区块和交易的缓存：
将block和txhash的缓存分开存储，各自有对应的可配置选项
1.BlockCache 只缓存最新的区块，缓存的大小由defCacheSize配置项决定，默认缓存128最新的区块
2.TxCache只缓存交易hash值，方便交易去重时快速查找，缓存的大小由highAllowPackHeight + lowAllowPackHeight 配置项之和决定。默认是120区块的所有交易hash，最大不能超过5000个
> add by hyb for issues-822

- blockchain/download.go
- blockchain/process.go
- types/tx.go
修改：
1.快速下载模式时区块执行失败，清除快速下载的标识以及删除此执行失败区块从数据库缓存中
2.快速下载模式时区块执行失败，不记录错误故障并删除index中本区块的缓存，方便普通模式时再次下载本区块并执行
fix #955
> add by hyb for issues-955

- system/p2p/dht/manage/connectionGater.go
- system/p2p/dht/manage/connectionGater_test.go
- system/p2p/dht/p2p.go
发现如果不调整这个配置，系统在极端情况连接数达到上限之前，就会提前限制对方节点连进来 @yann-sjtu
> 调整系统的连接数最低和最高配置

- system/p2p/dht/p2p.go
解决RoutingDiscovery启动顺序引发的bug
fix #973 closed #973
> fix discovery init bug

- rpc/http.go
- rpc/server.go
- rpc/server_test.go
- types/cfg.go
RPC配置项增加：
//basic auth 用户名
JrpcUserName string `json:"jrpcUserName,omitempty"`
//basic auth 用户密码
JrpcUserPasswd string `json:"jrpcUserPasswd,omitempty"`
1.增加RPC接口的JsonRPC BasicAuth 用户名和密码访问的配置项
2. 如果不填写此配置，默认不启用
> 增加rpc的用户名和密码访问认证

- blockchain/chain.go
- blockchain/chain_duptx_test.go
- blockchain/proc.go
- blockchain/query_block.go
- system/mempool/base.go
- system/mempool/cache.go
- system/mempool/check.go
- system/mempool/eventprocess.go
- system/mempool/mempool_test.go
- types/const.go
- util/util.go
- util/util_test.go
1. mempool获取交易时，增加过期判定以及对过期的交易进行删除删除, 相关问题33cn/plugin#948, 33cn/plugin#954, 33cn/plugin#961
2. fix #822 , 增加txHeight允许打包区间，默认设为300，支持配置，对于1w交易的区块，交易哈希缓存内存开销约90MB
> Fix mempool expired tx removing

- blockchain/blockstore.go
- blockchain/blocksyn.go
- blockchain/chain.go
- system/p2p/dht/protocol/p2pstore/query.go
采用数据分片后个别节点出现同步异常的问题，经排查为请求的chunkhash是错误的。
目前的分片同步策略为：
1. 从任意节点同步chunkhash，作为请求chunk数据的索引
2. 根据chunkhash请求chunk数据
考虑到大部分节点为诚实节点，目前chunkhash的校验方案比较简单，从多个节点请求chunkhash，若存在不一致则取多数节点都认可的chunkhash。目前仍存在节点同步到错误的chunkhash的情况，导致根据错误的chunkhash无法找到分片数据。解决方案是监测到区块高度超过3分钟不增长时，从当前高度重新同步chunkhash，测试可以解决区块同步异常的问题。
ps: 若没有连接上其他节点则不删除本地chunkhash。
目前没有定位到保存了错误chunkhash的节点，当前代码已通过日志记录了chunkhash的来源节点，需要通过日志进一步定位
close #1026
> Redownload chunkhash

- system/p2p/dht/p2p.go
- system/p2p/dht/p2p_test.go
dht 配置项中统一使用 p2p 根配置项中指定的 dbPath，便于 bityuan 中重新指定 datadir 目录。
> update p2pstore datadir

- system/p2p/dht/protocol/p2pstore/handler.go
- system/p2p/dht/protocol/p2pstore/p2pstore.go
- system/p2p/dht/protocol/p2pstore/query.go
- system/p2p/dht/protocol/p2pstore/republish.go
- system/p2p/dht/types/const.go
- system/p2p/dht/types/types.go
从连接的其他节点获取更多节点信息，生成一个至少有200个节点信息的扩展路由表，防止连接节点数太少导致网络的局部性问题
> Update extend routing table

- common/crypto/sha3/xor_unaligned.go
fixed https://github.com/33cn/plugin/issues/1003
开启`race`时默认开启`checkptr`，此时长度为n的[]byte只能转换为长度不超过 n/8的[]uint64，否则runtime检查会报错堆对象越界，导致unsafe强制类型转换失败。该pr用于修复plugin的单元测试报错
参考：
https://golang.org/src/runtime/checkptr.go?s=194:258#L1
https://github.com/etcd-io/bbolt/issues/187
https://github.com/golang/go/issues/34964
https://go-review.googlesource.com/c/net/+/203400/2/ipv4/control_bsd.go
> fix pointer conversion bug of go1.14

- system/p2p/dht/manage/conns.go
libp2p存在对一个peer 同时有多个连接的情况，所以只统计connect的连接数是不够准确的
调整为统计连接的peer的数量
> fix issue #1082

- wallet/wallet_proc.go
1.因为当前的实现是如果签名的时候设置了交易费，就会按照设置的交易费来设置，而不管其是否满足根据交易体积大小的限制；这样的设置一个小的值，就会不能通过交易池的交易费检查机制；
2.evm提供了gas估算功能功能，对于部分的交易来说，估算出来的gas如果小于根据交易大小计算出来的交易费的，这时候如果让前端再来根据交易大小进行交易费的计算比较，就有点费事情了，所以在ProcSignRawTx该函数内部，把传入的交易费大小和根据交易体积大小计算出来的交易费二者取其大就好了
> modify fee set for ProcSignRawTx

- blockchain/process.go
- blockchain/query_block.go
- blockchain/reduce.go
- executor/execenv.go
- executor/executor.go
- executor/plugin_fee.go
- executor/plugin_txindex.go
- system/consensus/solo/solo.go
- system/consensus/solo/solo_test.go
- system/mempool/accountindex.go
- system/mempool/cache.go
- system/mempool/lasttx.go
- system/mempool/shorthashtx.go
- types/bench_test.go
- types/cfg.go
- types/executor.go
- types/tx.go
- types/types.go
- util/exec.go
- util/util.go
- wallet/wallet_proc.go
8核16g, 5w执行并发
- 支持相关索引开关配置, 可在性能测试模式下关闭
- 支持关闭交易查重
直接实现交易哈希缓存,涉及跨模块,比较困难, 主要通过以下几个方面缓解交易哈希计算带来的gc,cpu计算等问题
- 计算哈希时使用的交易对象,采用内存池复用
- probuf编码接口支持输入复用buffer参数, 对于交易结构的buffer使用内存池
- mempool相关接口复用交易哈希计算, 减少重复计算问题
优化细节执行流程,提高效率
>  Improve solo performance

- system/p2p/dht/protocol/p2pstore/query.go
增加一个路由缓存，连续的1000个块属于同一个chunk，会保存在同一个节点上。路由到一个chunk之后添加路由缓存，若后续请求的区块属于同一个chunk，则直接向路由缓存里的节点请求
> update: fetch chunk from cache provider

- system/mempool/check.go
在mempool 非常拥堵的时候，做适当的sleep ，减少交易丢失的数量。
> have a sleep when mempool is full

- system/p2p/dht/p2p.go
- system/p2p/dht/types/types.go
fix #1117, 增加libp2p库内部日志文件配置,  便于问题调试, 默认不开启
> fix issue 1117

- system/p2p/dht/protocol/p2pstore/handler.go
- system/p2p/dht/protocol/p2pstore/query.go
- system/p2p/dht/protocol/p2pstore/refresh.go
- system/p2p/dht/protocol/peer/peerinfo.go
libp2p stream超时控制分为两个部分，一个是建立stream（即数据流，基于节点之间的tcp连接）耗时，另一个是从stream中读写数据的耗时。
1. 节点之间建立新的tcp连接耗时为毫秒级别，基于tcp连接建立stream耗时为微妙级别，通过NewStream接口的context进行控制。节点拥堵时该耗时会变长，因此统一设置NewStream的超时为3秒，超过3秒则选择另外的节点进行通信。由于查询分片数据会与比较多的节点进行通信，所以该超时时间对获取分片数据的耗时的影响无法忽略。
2. 节点之间通过stream读写数据则根据数据量的多少有不同的耗时，通过stream.SetDeadline来进行超时控制，不同的业务逻辑应根据具体的通信数据设定合理的超时时间。
> update: set libp2p new stream timeout to 3s

- system/consensus/solo/solo.go
- system/p2p/dht/extension/pubsub.go
- system/p2p/dht/types/types.go
fix #1127 
1. 适配新版pubsub库, 支持最大发布数据大小可配置, 内置的为 1MB
2. 默认最大数据大小为chain33支持的最大区块, 即20MB
> dht:add maxMsgSize config for pubsub

- system/p2p/dht/extension/pubsub.go
- system/p2p/dht/extension/trace.go
- system/p2p/dht/extension/trace_test.go
- system/p2p/dht/protocol/broadcast/pubsub.go
dht pubsub 消息事件跟踪器实现, 主要是对底层sub丢弃的消息进行缓存, 进行二次分发
> Add pubsub tracer

- blockchain/push.go
- blockchain/push_test.go
目前推送３次失败后，会将该订阅的状态设置为inactive；
如果订阅重新激活，没有将其状态修改为active，
此时如果chain33重启，就不会自动推送，
所以需要在重新激活时，将状态修改为acvite(如果是非active的话)
> push重新开始后更新数据库状态

- types/tx.go
- types/tx_test.go
Protobuf提供的Reset接口可能导致哈希等计算不稳定, 增加reset方法,保证稳定性
> add transaction reset method

- wallet/bipwallet/bipwallet.go
- wallet/bipwallet/bipwallet_test.go
- wallet/bipwallet/transformer/btcbase/loader.go
close #1253 钱包支持新的cointype 898. 
Assetchain 是基于chain33 框架的新的公链
> wallet support cointype 898

- blockchain/blocksyn.go
- system/p2p/dht/protocol/broadcast/pubsub.go
- system/p2p/dht/protocol/broadcast/validate.go
- system/p2p/dht/protocol/broadcast/validate_test.go
1. 批量交易广播增加实时验证, 避免错误交易可能导致的泛洪问题
2. 移除blockchain启动时分叉检测任务, 由定时任务完成检测即可
> Fix broadcast batchtx

- .github/workflows/automake.yml
- .github/workflows/release.yml
- .releaserc.yml
- system/dapp/commands/wallet.go
- 增加签名和发送批量交易命令（**数据在指定文件中按行排列**）
- 扩展wallet sign命令， -d指定数据文件时，执行从文件中解析数据批量签名， -o指定输出文件（默认sign.out）
- 扩展wallet send命令， -d指定数据文件时，执行从文件中解析数据批量发送
> add sign and send txs in file

- .github/workflows/build.yml
- account/account_test.go
- cmd/chain33/chain33.fork.toml
- cmd/chain33/chain33.system.fork.toml
- common/address/util.go
- common/address/util_test.go
- system/address/eth/address.go
- system/address/eth/address_test.go
- system/dapp/manage/executor/exec.go
- system/dapp/manage/executor/manage.go
- types/config.go
- types/fork.go
增加系统eth地址格式化分叉,  修复合约中存在的地址比较兼容性
> Fix eth address format
